use_gpu: True
device: 0
early_stop:
  patience: 0
seed: 12345
federate:
  mode: standalone
  total_round_num: 2000
  client_num: 18
  merge_test_data: True
#  sample_client_rate: 0.2
data:
  root: data/
  type: shakespeare
#  subsample: 0.1
  splits: [0.6,0.2,0.2]
  splitter: 'lda'
  splitter_args: [{'alpha': 0.2}]
model:
  type: lstm
  in_channels: 80
  out_channels: 80
  embed_size: 8
#  hidden: 256
#  dropout: 0.0
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    lr: 2
    weight_decay: 0.0
criterion:
  type: character_loss
trainer:
  type: nlptrainer
eval:
  freq: 20
  metrics: ['acc', 'correct']
  best_res_update_round_wise_key: 'test_acc'
asyn:
  use: True
  min_received_rate: 0.167
  staleness_toleration: 1000
  aggregator: 'goal_achieved'
  broadcast_manner: 'after_receiving'
usrsele:
  use: True
  strategy: 'fast' # 三种选择，fast, combi, coor_group
  factor: 0.5 # 用户抽选比例
  ablation: 'none' # fast-s，combi-s (不考虑用户基于累计历史分布的用户selection)；
  #  fast-w, combi-w (不考虑用内外相似性调节weights); none
usrsele_compa_hfl:
  use: False
  factor: 0.5
usrsele_compa_schandagg:
  use: False
  gamma: 0.8
usrsele_compa_freqandage:
  use: False
  factor: 0.5
  gamma: 0.8
usrsele_compa_kafl:
  use: False
  rho: 0.5
usrsele_compa_aouprior:
  use: False
  factor: 0.5
usrsele_compa_wkafl:
  use: False
  cb1: 300
  cb2: 5