use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  total_round_num: 1000
  sample_client_num: 30
  client_num: 118
  merge_test_data: False
#  sample_client_rate: 0.2
data:
  root: data/
  type: shakespeare
  subsample: 0.1
  splits: [0.8,0.0,0.2]
model:
  type: lstm
  in_channels: 80
  out_channels: 80
  embed_size: 8
  hidden: 256
  dropout: 0.0
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    lr: 0.8
    weight_decay: 0.0
criterion:
  type: character_loss
trainer:
  type: nlptrainer
eval:
  freq: 50
  metrics: ['acc', 'correct']
  best_res_update_round_wise_key: 'test_acc'
asyn:
  use: True
  overselection: False
  staleness_discount_factor: 0.2
  aggregator: 'goal_achieved'
  broadcast_manner: 'after_receiving'
  min_received_num: 10
  staleness_toleration: 1000
nbafl:
  use: True
  epsilon: 8.4
  w_clip: 0.01
  constant: 2
  mu: 0
wandb:
  use: True
  name_user: gogll2218
  name_project: shakes_silo_a
  online_track: True
  client_train_info: True