use_gpu: True
device: 0
early_stop:
  patience: 0
seed: 2
federate:
  mode: standalone
  total_round_num: 3000
  sample_client_num: 30
  merge_test_data: False
  share_local_model: False
  client_num: 100
#  sampler: 'uniform'
#  resource_info_file: 'client_device_capacity'
data:
  root: data/
  type: femnist
  args: [{'download': True}]
  splits: [0.8,0.0,0.2]
#  subsample: 0.2
  transform: [['ToTensor'], ['Normalize', {'mean': [0.4914], 'std': [0.2470]}]]
#  splitter: 'lda'
#  splitter_args: [{'alpha': 0.2}]
dataloader:
  batch_size: 64
model:
  type: vgg11
#  hidden: 512
  out_channels: 62
train:
  local_update_steps: 1
  batch_or_epoch: batch
  optimizer:
    lr: 1
    weight_decay: 0.0
grad:
  grad_clip: -1
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 50
  metrics: ['acc', 'correct']
  best_res_update_round_wise_key: 'test_acc'
asyn:
  use: True
  overselection: False
  staleness_discount_factor: 0.2
  aggregator: 'goal_achieved'
  broadcast_manner: 'after_receiving'
  min_received_num: 10
  staleness_toleration: 1000
adaclip1:
  use: True
  beta_1: 0.99 # 超参，可调
  beta_2: 0.9 # 超参，可调
  h_1: 1e-8 # 超参，可调
  h_2: 1e-8 # 超参，可调
  clipbound: 1. # 裁剪大小
  n2s: 0.8 # 噪声与信号比
  lr: 1 # 学习率
  M: [] # 存储中间参量，每层的均值
  S: [] # 存储中间参量，每层的标准差
wandb:
  use: True
  name_user: gogll2218
  name_project: femnist_425_silo_asyn
  online_track: True
  client_train_info: True

