use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  total_round_num: 1000
  sample_client_num: 24
  client_num: 118
  merge_test_data: True
#  sample_client_rate: 0.2
data:
  root: data/
  type: shakespeare
  subsample: 0.1
  splits: [0.8,0.0,0.2]
model:
  type: lstm
  in_channels: 80
  out_channels: 80
  embed_size: 8
  hidden: 256
  dropout: 0.0
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    lr: 1
    weight_decay: 0.0
criterion:
  type: character_loss
trainer:
  type: nlptrainer
eval:
  freq: 50
  metrics: ['acc', 'correct']
  best_res_update_round_wise_key: 'test_acc'
asyn:
  use: True
  overselection: False
  staleness_discount_factor: 0.2
  aggregator: 'goal_achieved'
  broadcast_manner: 'after_receiving'
  min_received_num: 12
  staleness_toleration: 1000
mapa:
  use: True
  grad_var: 5. # 梯度方差，可调
  clipbound: 8. # 初始梯度裁剪上界， 可调
  redcu_ratio: 0.8 # 衰减率
  L_smooth: 0.0004 # 光滑度，可调
  inital_loss_bound: 5. # 初始损失函数上界，可调
  n2s: 0.8 # 噪声与信号比
  style: 'sample' # 差分隐私对象，另一种为'client'
