use_gpu: True
device: 0
early_stop:
  patience: 0
seed: 2
federate:
  mode: standalone
  total_round_num: 2000
  sample_client_num: 32 # 18*6
  merge_test_data: True
  share_local_model: False
  client_num: 800 #180*6
#  sampler: 'uniform'
#  resource_info_file: 'client_device_capacity'
data:
  root: data/
  type: celeba
  args: [{'download': True}]
  splits: [0.8,0.0,0.2]
#  subsample: 0.2
  transform: [['ToTensor'], ['Normalize', {'mean': [0.4914, 0.4822, 0.4465], 'std': [0.2470, 0.2435, 0.2616]}]]
#  splitter: 'lda'
#  splitter_args: [{'alpha': 0.2}]
dataloader:
  batch_size: 5
model:
  type: vgg11
#  hidden: 512
  out_channels: 2
train:
  local_update_steps: 1
  batch_or_epoch: batch
  optimizer:
    lr: 0.1
    weight_decay: 0.0
grad:
  grad_clip: -1
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 50
  metrics: ['acc', 'correct']
  best_res_update_round_wise_key: 'test_acc'
asyn:
  use: True
  overselection: False
  staleness_discount_factor: 0.2
  aggregator: 'goal_achieved'
  broadcast_manner: 'after_receiving'
  min_received_num: 16 # 9*6
  staleness_toleration: 1000
median:
  use: True
  n2s: 0.8
wandb:
  use: False
  name_user: gogll2218
  name_project: celeba_fixdps
hpo:
  scheduler: sha
  num_workers: 0
  init_cand_num: 9
  ss: 'scripts/pami_camparison_algorithms/dp_ss.yaml'
  sha:
    budgets: [ 3, 9 ]
    elim_rate: 3
    iter: 1
  metric: 'server_global_eval.test_loss'
  working_folder: sha

