use_gpu: True
device: 0
early_stop:
  patience: 0
seed: 2
federate:
  mode: standalone
  total_round_num: 6000
  sample_client_num: 32
  merge_test_data: True
  share_local_model: False
  client_num: 800 #180*6
#  sampler: 'uniform'
#  resource_info_file: 'client_device_capacity'
data:
  root: data/
  type: celeba
  args: [{'download': True}]
  splits: [0.8,0.1,0.1]
#  subsample: 0.2
  transform: [['ToTensor'], ['Normalize', {'mean': [0.4914, 0.4822, 0.4465], 'std': [0.2470, 0.2435, 0.2616]}]]
#  splitter: 'lda'
#  splitter_args: [{'alpha': 0.2}]
dataloader:
  batch_size: 32
model:
  type: vgg11
#  hidden: 512
  out_channels: 2
train:
  local_update_steps: 1
  batch_or_epoch: batch
  optimizer:
    lr: 0.01
    weight_decay: 0.0
grad:
  grad_clip: -1
criterion:
  type: CrossEntropyLoss
trainer:
  type: cvtrainer
eval:
  freq: 50
  metrics: ['acc', 'correct']
  best_res_update_round_wise_key: 'test_acc'
asyn:
  use: True
  overselection: False
  staleness_discount_factor: 0.2
  aggregator: 'goal_achieved'
  broadcast_manner: 'after_receiving'
  min_received_num: 16
  staleness_toleration: 1000
mapa:
  use: False
  grad_var: 50. # 梯度方差，可调
  grad_bound: 100. # 初始梯度裁剪上界， 可调
  redcu_ratio: 0.8 # 衰减率
  L_smooth: 0.000004 # 光滑度，可调
  inital_loss_bound: 1000. # 初始损失函数上界，可调
  n2s: 0.0 # 噪声与信号比
  style: 'sample' # 差分隐私对象，另一种为'client'
adaclip1:
  use: False
  beta_1: 0.99 # 超参，可调
  beta_2: 0.9 # 超参，可调
  h_1: 1e-12 # 超参，可调
  h_2: 1e-10 # 超参，可调
  clipbound: 1. # 裁剪大小
  n2s: 0.8 # 噪声与信号比
  M: [] # 存储中间参量，每层的均值
  S: [] # 存储中间参量，每层的标准差
adaclip2:
  use: False
  quatile: 0.5  # 梯度裁剪与梯度大小比例
  c: 0.5  # 隐私预算分配
  clipbound: 0.8  # 梯度裁剪大小
  n2s: 0.8 # 噪声与信号比
  clipbound_us: 'Lin' # 梯度裁剪更新方式，可选'Geo'
fixdps:
  use: False
  clipbound: 18
  n2s: 0.8
fixdpc:
  use: False
  clipbound: 20
  n2s: 0.8
wandb:
  use: True
  name_user: gogll2218
  name_project: celeba_nondp
  online_track: True
  client_train_info: True

